export * from "./customer.schema.ts";
export * from "./street.schema.ts";
export * from "./city.schema.ts";
export * from "./mobile.phone.schema.ts";
export * from "./house.number.schema.ts";
export * from "./name.schema.ts";
export * from "./zipcode.schema.ts";
export * from "./email.schema.ts";
export * from "./gdpr.schema.ts";
